name: 🐛 Bug Report
description: File a bug report to help us improve VelocityNvim
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please search existing issues before creating a new one
      options:
        - label: I have searched existing issues
          required: true

  - type: input
    id: neovim-version
    attributes:
      label: Neovim Version
      description: Output of `nvim --version`
      placeholder: "NVIM v0.11.0"
    validations:
      required: true

  - type: input
    id: velocity-version
    attributes:
      label: VelocityNvim Version
      description: Output of `:VelocityInfo` or git commit hash
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - WSL2
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Start VelocityNvim with `NVIM_APPNAME=VelocityNvim nvim`
        2. Open file '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please copy and paste any relevant log output or error messages
      render: shell

  - type: textarea
    id: health-check
    attributes:
      label: Health Check Output
      description: Output of `:VelocityHealth` command
      render: shell

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here