name: RSS Feed Update

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Generate RSS Feed
        run: |
          mkdir -p docs/feeds

          # Create feed header
          cat > docs/feeds/releases.xml << 'HEADER_EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <feed xmlns="http://www.w3.org/2005/Atom">
            <title>VelocityNvim Releases</title>
            <link href="https://github.com/Maik-0000FF/VelocityNvim"/>
          HEADER_EOF

          # Add timestamp
          echo "  <updated>$(date -u +%Y-%m-%dT%H:%M:%SZ)</updated>" >> docs/feeds/releases.xml

          # Fetch releases and convert to XML with proper escaping
          curl -s "https://api.github.com/repos/Maik-0000FF/VelocityNvim/releases?per_page=10" | \
          jq -r '.[] |
            "  <entry>\n" +
            "    <title>" + (.name | @html) + "</title>\n" +
            "    <link href=\"" + .html_url + "\"/>\n" +
            "    <id>" + .html_url + "</id>\n" +
            "    <updated>" + .published_at + "</updated>\n" +
            "    <content type=\"html\"><![CDATA[" + (.body // "") + "]]></content>\n" +
            "  </entry>"' >> docs/feeds/releases.xml

          # Close feed
          echo "</feed>" >> docs/feeds/releases.xml

          echo "✅ RSS Feed generated successfully"
          cat docs/feeds/releases.xml

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update RSS feed for IFTTT"
          branch: auto-rss-update
          base: main
          delete-branch: true
          title: "Auto-update RSS feed"
          body: |
            Automated RSS feed update for IFTTT/Reddit automation

            - Updated feed with latest releases
            - Timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)
          labels: automation
          committer: VelocityNvim RSS Bot <rss-bot@velocitynvim.github>
          author: VelocityNvim RSS Bot <rss-bot@velocitynvim.github>

      - name: Enable auto-merge
        if: steps.create-pr.outputs.pull-request-number != ''
        run: gh pr merge --auto --squash ${{ steps.create-pr.outputs.pull-request-number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
